/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jsbd_voice_jni_XfMicJNI */

#ifndef _Included_com_jsbd_voice_jni_XfMicJNI
#define _Included_com_jsbd_voice_jni_XfMicJNI

/*------ xfmic ------*/
#define ENTER_PASSBY_MODE _IOR('X', 1, int)
#define ENTER_NR_MODE _IOR('X', 2, int)
#define ENTER_MUTE_MODE _IOR('X', 3, int)
#define ENTER_UNMUTE_MODE _IOR('X', 4, int)
#define ENTER_WAKEUP_MODE _IOR('X', 5, int)
#define GET_MODE_STATE _IOR('X', 6, int)

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jsbd_voice_jni_XfMicJNI
 * Method:    SetXfmicMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_jsbd_voice_jni_XfMicJNI_SetXfmicMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jsbd_voice_jni_XfMicJNI
 * Method:    GetXfmicMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jsbd_voice_jni_XfMicJNI_GetXfmicMode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
